### ISSUE TITLE
关于极限情况下使用timer类的讨论

### ISSUE THREAD

**Issue by ChunelFeng** [LonnyChason/ModernCppTimer#1]
```cpp
    ModernCppTimer timer;
    timer.start(1000, [] {
        printf("hello, world");
        sleep(3000);
    });

    sleep(5500)
    timer.stop();
```

程序在执行上述代码的时候，无法正常退出，建议修改start()函数中的内容 为：

```cpp

future_ = std::async(std::launch::async, [this, interval, task]() {
     while (!is_stop_) {
         CGRAPH_UNIQUE_LOCK lk(mutex_);
         const auto result = cv_.wait_for(lk, std::chrono::milliseconds(interval));
         if (std::cv_status::timeout == result) {
             task();
         }
     }
});

```

**Comment by LonnyChason** [comment]
感谢大佬指点，已采纳，谢谢！

**Comment by ChunelFeng** [comment]
赞赞赞，已经将此版本搞成了我这边库的一个工具组件

https://github.com/ChunelFeng/CGraph/blob/main/src/UtilsCtrl/Timer/UTimer.h

感谢分享。

**Comment by LonnyChason** [comment]
哈哈，共同学习，造出更好、更稳定的轮子。不过这个timer在linux下更改系统时间可能会存在提前触发的问题，详见我的知乎回答的评论区。https://www.zhihu.com/question/38427301/answer/2291441670. 另外也有人喷我性能差爆了，也有喷这不叫定时器，这叫玩具，没有任何实用价值（https://zhuanlan.zhihu.com/p/451515242）害，也不知道Windows下还有没有比这更优雅、高效的实现了。共同探讨一下。
